name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.414'

      - name: Restore & Test API
        run: |
          dotnet restore src/api/ProjectHub.sln
          dotnet build src/api/ProjectHub.sln --no-restore -c Release
          dotnet test src/api/ProjectHub.sln --no-build

      - name: Verify API formatting
        run: dotnet format src/api/ProjectHub.sln --verify-no-changes

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'

      - name: Install & Build Web
        working-directory: src/web
        run: |
          npm ci
          npm run format
          npm run build
