name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Test API
        run: |
          dotnet restore src/api/ProjectHub.sln
          dotnet build src/api/ProjectHub.sln --no-restore -c Release
          dotnet test src/api/ProjectHub.sln --no-build

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Test Web
        working-directory: src/web
        run: |
          npm ci
          npm run typecheck || true
          npm run test || true
