services:
  api:
    build:
      context: ../../
      dockerfile: ops/docker/Dockerfile.api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: Server=sqlserver.tail5b1945.ts.net;Database=ProjectHub;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=true
    ports:
      - "8080:8080"
    restart: unless-stopped

  web:
    build:
      context: ../../
      dockerfile: ops/docker/Dockerfile.web
    ports:
      - "5173:80"
    depends_on:
      - api
    restart: unless-stopped
