FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY src/api ./api
RUN dotnet restore api/ProjectHub.Api/ProjectHub.Api.csproj
RUN dotnet publish api/ProjectHub.Api/ProjectHub.Api.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app ./
EXPOSE 8080
ENTRYPOINT ["dotnet", "ProjectHub.Api.dll"]
